defaults: &defaults
  event:
    name: "Isle of Ruby"
    start_time: 2018-04-10 00:00:00
    end_time: 2018-04-18 23:59:59
  host: "activities.isleofruby.org"
  mailers:
    from: "activities@isleofruby.org"
  errors:
    from: "exception@isleofruby.org"
    to:
      - "cfp-errors@isleofruby.org"
  seo:
    title: "Isle of Ruby"
    author: "Isle of Ruby team"
    description: "List of events at and around Isle of Ruby"

development:
  <<: *defaults
  host: "activities.dev:3000"

test:
  <<: *defaults
  event:
    name: "Isle of Ruby"
    start_time: 2018-04-10 00:00:00
    end_time: 2018-04-18 23:59:59

staging:
  <<: *defaults
  host: "TBD"

production:
  <<: *defaults
